const restaurantData = [
    {
        id: 1,
        image: 'https://images.pexels.com/photos/2878741/pexels-photo-2878741.jpeg?auto=compress&cs=tinysrgb&w=600',
        title: 'Barbecue Nation',
        subtitle: 'Vegetarian,Chicken,French Fries',
        distance: '5 Km',
        rating: '4.0',
        rating_count: '20+',
        priceForOne: '200',
        timeTaken: '30-35 mins',
        openingTime: '7:30 AM',
        closingTime: '10.30 PM',
        cuisines: ['North Indian', 'Chinese', 'Fast Food'],
    },
    {
        id: 2,
        image: 'https://images.pexels.com/photos/2878741/pexels-photo-2878741.jpeg?auto=compress&cs=tinysrgb&w=600',
        title: 'Barbecue Nation',
        subtitle: 'Vegetarian,Chicken,French Fries',
        distance: '5 Km',
        rating: '4.0',
        rating_count: '20+',
        priceForOne: '200',
        timeTaken: '30-35 mins',
        openingTime: '7:30 AM',
        closingTime: '10.30 PM',
        cuisines: ['North Indian', 'Chinese', 'Fast Food'],
    },
    {
        id: 3,
        image: 'https://images.pexels.com/photos/2878741/pexels-photo-2878741.jpeg?auto=compress&cs=tinysrgb&w=600',
        title: 'Barbecue Nation',
        subtitle: 'Vegetarian,Chicken,French Fries',
        distance: '5 Km',
        rating: '4.0',
        rating_count: '20+',
        priceForOne: '200',
        timeTaken: '30-35 mins',
        openingTime: '7:30 AM',
        closingTime: '10.30 PM',
        cuisines: ['North Indian', 'Chinese', 'Fast Food'],
    },
    {
        id: 4,
        image: 'https://images.pexels.com/photos/2878741/pexels-photo-2878741.jpeg?auto=compress&cs=tinysrgb&w=600',
        title: 'Barbecue Nation',
        subtitle: 'Vegetarian,Chicken,French Fries',
        distance: '5 Km',
        rating: '4.0',
        rating_count: '20+',
        priceForOne: '200',
        timeTaken: '30-35 mins',
        openingTime: '7:30 AM',
        closingTime: '10.30 PM',
        cuisines: ['North Indian', 'Chinese', 'Fast Food'],
    },
    {
        id: 5,
        image: 'https://images.pexels.com/photos/2878741/pexels-photo-2878741.jpeg?auto=compress&cs=tinysrgb&w=600',
        title: 'Barbecue Nation',
        subtitle: 'Vegetarian,Chicken,French Fries',
        distance: '5 Km',
        rating: '4.0',
        rating_count: '20+',
        priceForOne: '200',
        timeTaken: '30-35 mins',
        openingTime: '7:30 AM',
        closingTime: '10.30 PM',
        cuisines: ['North Indian', 'Chinese', 'Fast Food'],
    },
];

export default restaurantData;
