export const BASE_URL =  'https://3136-180-151-107-110.ngrok.io/api/v1';
export const GET_CONFIG = 'GET_CONFIG';
export const GET_CONFIG_ERROR = 'GET_CONFIG_ERROR';
export const GOOGLE_MAPS_APIKEY = 'AIzaSyBp4AkSHWTMsEq7WVmcIgNQELjBrWr9puQ';
export const ORDER_BUFFER_TIME = 0;
export const CART_LIMIT = 3;
export const TAB_BAR_HEIGHT = 87; // Default tab bar height is 50
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const GET_ALL_ADDRESS = 'GET_ALL_ADDRESS';
export const SET_DEFAULT_ADDRESS = 'CHANGE_DEFAULT_ADDRESS';
export const UNSET_DEFAULT_ADDRESS = 'UNSET_DEFAULT_ADDRESS';
export const GET_DEFAULT_ADDRESS = 'GET_DEFAULT_ADDRESS';
export const GET_LIVE_LOCATION = 'GET_LIVE_LOCATION';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const CART_EXCEEDS_LIMIT = 'CART_EXCEEDS_LIMIT';
export const PLACE_ORDER_BY_USER = 'PLACE_ORDER_BY_USER';
export const PLACE_ORDER = 'PLACE_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const GET_CURRENT_ORDER = 'GET_CURRENT_ORDER';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const SEARCH_RESTAURANT = 'SEARCH_RESTAURANT';
export const SEARCH_FOODITEM = 'SEARCH_FOODITEM';
export const SEARCH_RESTAURANT_AND_FOODITEMS =
    'SEARCH_RESTAURANT_AND_FOODITEMS';
export const EMPTY_SEARCH = 'EMPTY_SEARCH';
export const PAYMENT_INITIATED = 'PAYMENT_INITIATED';
export const PAYMENT_PENDING = 'PAYMENT_PENDING';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const PAYMENT_CANCEL = 'PAYMENT_CANCEL';
// export const REFUND_INITIATED = 'REFUND_INITIATED';
export const GET_ALL_PAYMENTS = 'GET_ALL_PAYMENTS';
export const RESET_ADDRESS = 'RESET_ADDRESS';
export const RESET_CURRENT_ORDER = 'RESET_CURRENT_ORDER';
export const RESET_ORDERS = 'RESET_ORDERS';
export const RESET_PAYMENTS = 'RESET_PAYMENTS';
export const RESET_SEARCH = 'RESET_SEARCH';
export const RESET_USER = 'RESET_USER';
export const CHECK_LOCATION_PERMISSION = 'CHECK_LOCATION_PERMISSION';
export const IS_LOCATION_ON = 'IS_LOCATION_ON';
export const NETWORK_ERROR = 'Network response was not ok';
export const UNEXPECTED_ERROR = 'Unexpected Error Occured';
export const FETCH_DATA_FAILURE_SEARCH = 'FETCH_DATA_FAILURE_SEARCH';
export const FETCH_DATA_FAILURE_ADDRESS = 'FETCH_DATA_FAILURE_ADDRESS';
export const FETCH_DATA_FAILURE_CURRENT_ORDER =
    'FETCH_DATA_FAILURE_CURRENT_ORDER';
export const FETCH_DATA_FAILURE_ORDERS = 'FETCH_DATA_FAILURE_ORDERS';
export const FETCH_DATA_FAILURE_PAYMENT = 'FETCH_DATA_FAILURE_PAYMENT';
export const FETCH_DATA_FAILURE_USER = 'FETCH_DATA_FAILURE_USER';
export const CART_ERROR = 'CART_ERROR';
export const GET_CART_CONFIG = 'GET_CART_CONFIG';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const APPLY_WALLET_MONEY = 'APPLY_WALLET_MONEY';
export const REMOVE_WALLET_MONEY_FROM_CART = 'REMOVE_WALLET_MONEY_FROM_CART';
export const CHANGE_CART_ADDRESS = 'CHANGE_CART_ADDRESS';
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL';
export const GET_USER_WALLET = 'GET_USER_WALLET';
export const RESET_CART_ACTIONS = 'RESET_CART_ACTIONS';
export const ADD_TO_CART_FOR_REORDER = 'ADD_TO_CART_FOR_REORDER';
export const CART_ACTIONS_ERROR = 'CART_ACTIONS_ERROR';
export const REDEEM_COUPON = 'REDEEM_COUPON';
export const REMOVE_COUPON = 'REMOVE_COUPON';
export const RESET_CART_ERROR = 'RESET_CART_ERROR';
export const RESET_ADDRESS_ERROR = 'RESET_ADDRESS_ERROR';

//short

export const SHORTS = 'SHORTS';
export const SHORTS_SUCCESS = 'SHORTS_SUCCESS';
export const SHORTS_FAIL = 'SHORTS_FAIL';

export const REMOVE_FOLLOWED_FROKER = 'REMOVE_FOLLOWED_FROKER';
export const RESET_FOLLOWED_FROKER = 'RESET_FOLLOWED_FROKER';
export const SET_FOLLOWED_FROKER = 'SET_FOLLOWED_FROKER';

export const SET_HEADER_WITH_LOCATION_HEIGHT =
    'SET_HEADER_WITH_LOCATION_HEIGHT';

export const SET_INTERNET_AVAILABILITY = 'SET_INTERNET_AVAILABILITY';
export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';
export const MENU_MODAL = 'MENU_MODAL';

//subscription page constants starts from here

export const SUBSCRIPTION_SELECT_MENU_ITEM = 'SUBSCRIPTION_SELECTED_MENU_ITEM';
export const SUBSCRIPTION_RESET_SELECT_MENU_ITEM='SUBSCRIPTION_RESET_SELECT_MENU_ITEM'

export const SUBSCRIPTION_VEG_MENU_ONLY_TRUE = 'SUBSCRIPTION_VEG_MENU_ONLY_TRUE';
export const SUBSCRIPTION_VEG_MENU_ONLY_FALSE="SUBSCRIPTION_VEG_MENU_ONLY_FALSE";

export const SUBSCRIPTION_MEAL_NUMBER_INCREASED = 'SUBSCRIPTION_MEAL_NUMBER_INCREASED';
export const SUBSCRIPTION_MEAL_NUMBER_DECREASED = 'SUBSCRIPTION_MEAL_NUMBER_DECREASED';

export const FINAL_SUBSCRIPTION_MODEL_PRICE = 'FINAL_SUBCRIPTION_MODEL_PRICE';

//subscription cart constants starts from here
export const SUBSCRIPTION_ADD_TO_CART = 'SUBSCRIPTION_ADD_TO_CART';
export const SUBSCRIPTION_REMOVE_FROM_CART = 'SUBSCRIPTION_REMOVE_FROM_CART';

//subscription meal type
export const SET_SUBSCRIPTION_MEAL_TYPE = 'SUBSCRIPTION_MEAL_TYPE';
export const RESET_SUBSCRIPTION_MEAL_TYPE = 'RESET_SUBSCRIPTION_MEAL_TYPE';
