export const REFUND_CODES = {
    BAD_REQUEST: 'BAD_REQUEST',
    AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
    TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    REVERSAL_WINDOW_EXCEEDED: 'REVERSAL_WINDOW_EXCEEDED',
    REFUND_SUCCESS: 'REFUND_SUCCESS',
    REFUND_PENDING: 'REFUND_PENDING',
    REFUND_ERROR: 'REFUND_ERROR',
};
